### ISSUE TITLE
Crash on IPv6 with missing local configuration

### ISSUE THREAD

**Issue by adrianrudnik** [adrianrudnik/fritzbox-cloudflare-dyndns#4]
Proxy crashes when calling http://localhost:41010/ip?v4=80.128.62.108&v6=2003:cc:7fff:1026:e228:6dff:fe68:3f04&prefix=2003:cc:7f10:1800::/56 if the `DEVICE_LOCAL_ADDRESS_IPV6` is not set.

**Comment by adrianrudnik** [comment]
Error log was

```
updater_1  | time="2021-02-10T19:24:54Z" level=info msg="Received incoming DynDNS update" module=dyndns
updater_1  | time="2021-02-10T19:24:54Z" level=info msg="Forwarding update request for IPv4" ipv4=80.128.62.108 module=dyndns
updater_1  | 2021/02/10 19:24:54 http: panic serving 192.168.79.1:40797: runtime error: index out of range [0] with length 0
updater_1  | goroutine 952 [running]:
updater_1  | net/http.(*conn).serve.func1(0xc000338000)
updater_1  |    /usr/local/go/src/net/http/server.go:1801 +0x147
updater_1  | panic(0x751300, 0xc00001a180)
updater_1  |    /usr/local/go/src/runtime/panic.go:975 +0x47a
updater_1  | github.com/adrianrudnik/fritzbox-cloudflare-dyndns/pkg/dyndns.(*Server).Handler(0xc000356640, 0x7ecf20, 0xc00036c0e0, 0xc00006e000)
updater_1  |    /appbuild/pkg/dyndns/server.go:75 +0xeca
updater_1  | net/http.HandlerFunc.ServeHTTP(0xc000415210, 0x7ecf20, 0xc00036c0e0, 0xc00006e000)
updater_1  |    /usr/local/go/src/net/http/server.go:2042 +0x44
updater_1  | net/http.(*ServeMux).ServeHTTP(0x9c76c0, 0x7ecf20, 0xc00036c0e0, 0xc00006e000)
updater_1  |    /usr/local/go/src/net/http/server.go:2417 +0x1ad
updater_1  | net/http.serverHandler.ServeHTTP(0xc00036c8c0, 0x7ecf20, 0xc00036c0e0, 0xc00006e000)
updater_1  |    /usr/local/go/src/net/http/server.go:2843 +0xa3
updater_1  | net/http.(*conn).serve(0xc000338000, 0x7ed5a0, 0xc000144000)
updater_1  |    /usr/local/go/src/net/http/server.go:1925 +0x8ad
updater_1  | created by net/http.(*Server).Serve
updater_1  |    /usr/local/go/src/net/http/server.go:2969 +0x36c
```
